# 这是生产环境的配置文件
server:
  port: 1111


logging:
  file:
    # 通过日志的名称
    # name: springboot.log
    # 通过日志的路径
    path: E:\code\web_code\spring_boot  #spring.log
  level:
    root: warn
    com:
      jiehfut: warn

spring:
  datasource:
    url: jdbc:mysql://xxxx:3306/testdb?characterEncoding=utf8
    username: root
    password: 959452